apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  labels:
    {{- include "catalog.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Chart.Name }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Chart.Name }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name }}
      securityContext:
        fsGroup: {{ .Values.securityContext.fsGroup }}
      {{- if .Values.topologySpreadConstraints }}
      topologySpreadConstraints:
        {{- range .Values.topologySpreadConstraints }}
        - maxSkew: {{ .maxSkew }}
          topologyKey: {{ .topologyKey }}
          whenUnsatisfiable: {{ .whenUnsatisfiable }}
          labelSelector:
            matchLabels:
              app.kubernetes.io/name: {{ $.Chart.Name }}
              app.kubernetes.io/instance: {{ $.Release.Name }}
        {{- end }}
      {{- end }}
      
      # initContainers:
      #   - name: otel-auto-instrumentation
      #     image: public.ecr.aws/aws-observability/aws-otel-auto-instrumentation:latest
      #     command:
      #       - /bin/sh
      #       - -c
      #       - |
      #         cp -r /otel-auto-instrumentation/* /otel-auto/
          # volumeMounts:
          #   - name: otel-auto
          #     mountPath: /otel-auto
      containers:
        - name: catalog
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          envFrom:
            - configMapRef:
                name: {{ .Chart.Name }}
          
          env:
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: http://otel-collector.aws-otel-collector.svc.cluster.local:4317

            - name: OTEL_EXPORTER_OTLP_PROTOCOL
              value: grpc

            - name: OTEL_SERVICE_NAME
              value: catalog-service

            - name: OTEL_RESOURCE_ATTRIBUTES
              value: service.name=catalog-service,service.namespace=retail

          ports:
            - name: http
              containerPort: {{ .Values.service.targetPort }}
          readinessProbe:
            httpGet:
              path: {{ .Values.healthCheck.path }}
              port: {{ .Values.service.targetPort }}
          livenessProbe:
            httpGet:
              path: {{ .Values.healthCheck.path }}
              port: {{ .Values.service.targetPort }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          securityContext:
            runAsNonRoot: true
            runAsUser: {{ .Values.securityContext.runAsUser }}
            readOnlyRootFilesystem: true
            capabilities:
              drop: ["ALL"]
          volumeMounts:
            - name: {{ .Values.secrets.volumeName }}
              mountPath: {{ .Values.secrets.mountPath }}
              readOnly: true
            # - name: otel-auto
            #   mountPath: /otel-auto
          command: ["/bin/bash", "-c"]
          args:
            - |
              export RETAIL_CATALOG_PERSISTENCE_USER=$(cat {{ .Values.secrets.mountPath }}/MYSQL_USER);
              export RETAIL_CATALOG_PERSISTENCE_PASSWORD=$(cat {{ .Values.secrets.mountPath }}/MYSQL_PASSWORD);
              export OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector.aws-otel-collector.svc.cluster.local:4317;
              export OTEL_EXPORTER_OTLP_PROTOCOL=grpc;
              export OTEL_SERVICE_NAME=catalog-service;
              exec /app/main
      volumes:
        - name: {{ .Values.secrets.volumeName }}
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: "{{ .Values.secrets.secretProviderClass }}"
        # - name: otel-auto
        #   emptyDir: {}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}