apiVersion: v1
kind: ServiceAccount
metadata:
  name: aws-cli-sa
  namespace: default
  labels:
    app.kubernetes.io/name: catalog
    app.kubernetes.io/instance: catalog
    app.kubernetes.io/component: service
    app.kubernetes.io/owner: retail-store-sample